version: '2'

services:
  apache:
    image: httpd:latest
    volumes:
      - ./apache:/usr/local/apache2/files
  web:
    build:
      context: ./
      dockerfile: server-php/docker/server/server-nginx.docker
    volumes_from:
      - app
    ports:
      - "8081:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: server-php/docker/php/app-php-5.6.docker
    depends_on:
      - rabbit
    volumes:
      - ./server-php/code:/var/www
    links:
      - rabbit
  worker1:
    build:
      context: ./
      dockerfile: workers/docker/php/app-php-5.6.docker
    command: php worker.php
    depends_on:
      - rabbit
    volumes:
      - ./workers/code:/var/www
    links:
      - rabbit
  worker2:
    build:
      context: ./
      dockerfile: workers/docker/php/app-php-5.6.docker
    command: php worker.php
    depends_on:
      - rabbit
    volumes:
      - ./workers/code:/var/www
    links:
      - rabbit
  worker3:
      build:
        context: ./
        dockerfile: workers/docker/php/app-php-5.6.docker
      command: php worker.php
      depends_on:
        - rabbit
      volumes:
        - ./workers/code:/var/www
      links:
        - rabbit
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"
      - "5672:5672"